spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/dengyaoyang/conf-repo
          username: 277153954@qq.com
          password: 1987277Dyy
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 8999